name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.11'
        architecture: x64
    - run: make build
    - run: venv-tools/bin/twine upload dist/*
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
